services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - ${app_port}:8000
    volumes:
      - ./data:/app/data
    environment:
      VMGD_API_CONFIG_FILE: .env.production

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: python run_scraper_schedule.py
    volumes:
      - ./data:/app/data
    environment:
      VMGD_API_CONFIG_FILE: .env.production
