"""add location slug

Revision ID: 702354718c7b
Revises: da2a6dd3b182
Create Date: 2023-05-16 20:19:02.615569

"""
from alembic import op
import sqlalchemy as sa

from app.utils.slugify import slugify


# revision identifiers, used by Alembic.
revision = '702354718c7b'
down_revision = 'da2a6dd3b182'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add column initially as nullable
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))

    # add slug to all existing locations
    conn = op.get_bind()
    s = sa.sql.select(sa.sql.text('* FROM location'))
    for row in conn.execute(s):
        slug = slugify(row.name)
        q = sa.sql.text(f'UPDATE location SET slug="{slug}" WHERE location.id == {row.id}')
        conn.execute(q)
    conn.commit()

    # set column as NOT NULL
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('slug', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
