"""ForecastDaily

Revision ID: 8240f84252c3
Revises: 86ec5d272f00
Create Date: 2023-04-26 20:18:45.925647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8240f84252c3'
down_revision = '86ec5d272f00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('minTemp', sa.Integer(), nullable=False),
    sa.Column('maxTemp', sa.Integer(), nullable=False),
    sa.Column('minHumi', sa.Integer(), nullable=False),
    sa.Column('maxHumi', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_daily_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_daily_id'))

    op.drop_table('forecast_daily')
    # ### end Alembic commands ###
