"""Session, Page, ForecastDaily

Revision ID: b12db961fd0c
Revises: 5e58e9557435
Create Date: 2023-04-28 09:59:53.227952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12db961fd0c'
down_revision = '5e58e9557435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('exception', sa.String(), nullable=False),
    sa.Column('html_hash', sa.String(), nullable=True),
    sa.Column('json_data', sa.String(), nullable=True),
    sa.Column('errors', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_error', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_error_id'), ['id'], unique=False)

    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_id'), ['id'], unique=False)

    op.create_table('forecast_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('minTemp', sa.Integer(), nullable=False),
    sa.Column('maxTemp', sa.Integer(), nullable=False),
    sa.Column('minHumi', sa.Integer(), nullable=False),
    sa.Column('maxHumi', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_daily_id'), ['id'], unique=False)

    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('json_data', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_id'))

    op.drop_table('page')
    with op.batch_alter_table('forecast_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_daily_id'))

    op.drop_table('forecast_daily')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_id'))

    op.drop_table('session')
    with op.batch_alter_table('page_error', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_error_id'))

    op.drop_table('page_error')
    # ### end Alembic commands ###
