"""Page

Revision ID: b1e355665955
Revises: 5e58e9557435
Create Date: 2023-03-28 21:04:25.996846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e355665955'
down_revision = '5e58e9557435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('json_data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_id'), ['id'], unique=False)

    op.create_table('page_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_error', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_error_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_error', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_error_id'))

    op.drop_table('page_error')
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_id'))

    op.drop_table('page')
    # ### end Alembic commands ###
